version: '3.6'

services:
  wakapi:
    image: ghcr.io/muety/wakapi:latest
    container_name: wakapi
    ports:
      - "3000:3000"
    environment:
      - WAKAPI_PASSWORD_SALT=${WAKAPI_PASSWORD_SALT}
    volumes:
      - wakapi-data:/data

  cloudflare:
    image: amit/cloudflared
    command: tunnel --no-autoupdate run --token ${TUNNEL_AUTH}
    depends_on:
      - wakapi
    restart: always
    

volumes:
  wakapi-data:
    external: true

